name: Repository Cards

on:
  workflow_dispatch:
    inputs:
      repo_author:
        description: "GitHub Username"
        required: true
        default: "your-username"
      repo_name:
        description: "Repository Name"
        required: true
        default: "your-repo"
      theme:
        description: "Card Theme"
        required: false
        default: "shades-of-purple"
      token:
        description: "Optional token override"
        required: false
        default: ""

  workflow_call:
    inputs:
      repo_author:
        type: string
        required: true
      repo_name:
        type: string
        required: true
      theme:
        type: string
        required: false
        default: "shades-of-purple"
    secrets:
      token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIVE_TOKEN: ${{ secrets.token || github.event.inputs.token || secrets.STATS || github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=${{ inputs.repo_author }}&repo=${{ inputs.repo_name }}&theme=${{ inputs.theme }}&show=reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage
          path: profile/${{ inputs.repo_author }} - repo=${{ inputs.repo_name }}.svg
          token: ${{ env.ACTIVE_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update Pin Card for ${{ inputs.repo_name }}" || exit 0
          git push
