name: Regenerate README Cards Daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  run-grs:
    uses: ./.github/workflows/github-readme-cards-gen.yml
    with:
      manual_repos: '[".github", "Cecil-ANSI-Utils", "Cecil-Bridge", "ANSI-Utils-Tester", "Cecil-Testers"]'
      repository_owner: "Cecil-Libraries"
      is_user: false
      theme: "shades-of-purple"
    secrets:
      token: ${{ secrets.STATS }}
